sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
notifications:
  email: false
language: node_js
node_js:
 - 8
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
 - curl -L https://cpanmin.us | sudo perl - App::cpanminus
 - sudo cpanm File::Slurper Data::Dump JSON MIME::Base64 HTTP::Tiny
install: make deps
script: make test
