## webpack stuff from https://serverless-stack.com/chapters/add-support-for-es6-es7-javascript.html
## express / test stuff from https://github.com/FrontendMasters/serverless-with-aws

service: NVRIS
app: nvris-dev

provider:
  name: aws
  runtime: nodejs12.x
  profile: nvris-dev
  region: us-east-1
  timeout: 10 # optional, in seconds, default is 6
  environment:
    NEW_RELIC_NO_CONFIG_FILE: true
  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - s3:*
  #     Resource: "arn:aws:s3:::ksvotes/*"

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-pseudo-parameters
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  hello:
    handler: src/index.handler
    layers:
# version 2 is intentional. later versions are broken.
      - arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:layer:image-magick:2
    timeout: 10 # optional, in seconds, default is 6
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
